name: flexiflow
description: "A new Flutter project."
version: 1.0.0
repository: https://github.com/luanemanuel/flexiflow/tree/master
issue_tracker: https://github.com/luanemanuel/flexiflow/issues

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
